# Install script for directory: /work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/work/01336/carson/VisIt/VisItDave/2.8.1")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "0")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/AMRTest/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/ANALYZE/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/ANSYS/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/AUXFile/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/AugDecomp/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/BOV/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/CEAucd/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/CMAT/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/CTRL/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Cube/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Curve2D/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/DDCMD/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Dyna3D/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/ExtrudedVol/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Fluent/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/FT2/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/GGCM/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/GHOST/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/GMV/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/GULP/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Gadget/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Image/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/LAMMPS/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Lines/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/MFIX/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/MM5/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/MatrixMarket/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Miranda/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/NASTRAN/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Nek5000/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/OVERFLOW/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/OpenFOAM/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/PATRAN/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/PuReMD/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/PLOT3D/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/PlainText/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/PLY/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Point3D/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/ProteinDataBank/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/RAW/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/SAR/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/SAS/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/STL/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Shapefile/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/SimV2/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Spheral/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/TFT/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/TSurf/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Tecplot/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/VASP/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/VTK/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/WPPImage/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/WavefrontOBJ/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/WellLogs/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/XSF/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/XYZ/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Xmdv/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/lata/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/volimage/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/unv/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/EnSight/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Claw/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/STAR/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Vis5D/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/ZipWrapper/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/VCellMTMD/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Cale/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/KullLite/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/PDB/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Silo/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/SAMI/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Vista/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/NETCDF/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/S3D/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Exodus/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/MFIXCDF/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/AMR/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/BATL/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/CaleHDF5/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/CarpetHDF5/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Chombo/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/CosmosPP/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Enzo/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/FLASH/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Geqdsk/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/GTC/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/H5Nimrod/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/M3D/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/M3DC1/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/PFLOTRAN/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Pixie/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/PVLD/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/SAMRAI/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/SXRIS/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Tetrad/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/UNIC/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Velodyne/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Vs/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/VisItXdmf/cmake_install.cmake")
  INCLUDE("/work/01336/carson/VisIt/VisItDave/visit2.8.1/src/databases/Uintah/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

